# Configuration de protection de branche au niveau maximal de sécurité
# Ce fichier définit les règles de protection pour la branche principale
# dans le format utilisé par l'API GitHub

protection:
  required_status_checks:
    strict: true
    contexts:
      - "verify_permissions"
      - "analyze"
      - "Analyze (javascript)"
      - "Analyze (python)"
      - "verify_secrets"
  
  # Exiger des revues de pull request avant la fusion
  required_pull_request_reviews:
    dismissal_restrictions:
      users: []
      teams: []
    require_code_owner_reviews: true
    required_approving_review_count: 1
  
  # Restreindre qui peut push sur cette branche
  restrictions:
    users: []
    teams: []
    apps: []
  
  # Exiger les signatures de commit signées
  required_signatures: true
  
  # Appliquer les protections aux administrateurs également
  enforce_admins: true
  
  # Bloquer les push qui contiennent des commits avec des sujets protégés
  block_creations: true
  
  # Exiger une conversation résolue avant la fusion
  required_conversation_resolution: true
  
  # Autorisations de branche
  allow_force_pushes: false
  allow_deletions: false
  required_linear_history: true
  
  # Exigences de déploiement
  required_deployments:
    enabled: true
    environments:
      - production