# FICHIER DE CONFIGURATION DES IDENTIFIANTS CLOUD ET API
# ATTENTION : Ne jamais commiter ce fichier dans Git (ajouté au .gitignore)
# Ce template ne contient que des valeurs d'exemple - remplacez-les par vos identifiants réels

# === IDENTIFIANTS AWS ===
aws:
  access_key_id: "VOTRE_AWS_ACCESS_KEY_ID"
  secret_access_key: "VOTRE_AWS_SECRET_ACCESS_KEY"
  region: "eu-west-1"  # Région principale

# === IDENTIFIANTS GOOGLE CLOUD ===
gcp:
  project_id: "VOTRE_GCP_PROJECT_ID"
  service_account_key_path: "./gcp-key.json"  # Chemin vers votre fichier JSON de compte de service
  region: "europe-west1"  # Région principale

# === IDENTIFIANTS AZURE ===
azure:
  subscription_id: "VOTRE_AZURE_SUBSCRIPTION_ID"
  tenant_id: "VOTRE_AZURE_TENANT_ID"
  client_id: "VOTRE_AZURE_CLIENT_ID"
  client_secret: "VOTRE_AZURE_CLIENT_SECRET"
  location: "westeurope"  # Région principale

# === IDENTIFIANTS API LLM POUR LE FALLBACK ===
llm:
  anthropic_api_key: "VOTRE_CLE_API_ANTHROPIC"
  openai_api_key: "VOTRE_CLE_API_OPENAI"

# === IDENTIFIANTS DOCKER HUB ===
docker:
  username: "VOTRE_USERNAME_DOCKER"
  password: "VOTRE_PASSWORD_DOCKER"
  email: "VOTRE_EMAIL_DOCKER"

# === CONFIGURATION RÉSEAU ===
network:
  aws_vpc_cidr: "10.0.0.0/16"
  azure_vnet_cidr: "10.1.0.0/16"
  
# === CONFIGURATION CLUSTER ===
cluster:
  gke:
    node_count: 3
    machine_type: "e2-standard-4"
    min_nodes: 2
    max_nodes: 10
  eks:
    node_count: 3
    instance_type: "t3.large"
    min_nodes: 2
    max_nodes: 10
  aks:
    node_count: 3
    vm_size: "Standard_D4s_v3"
    min_nodes: 2
    max_nodes: 10