name: Actionlint - Validation des workflows

on:
  push:
    paths:
      - '.github/workflows/**'
  pull_request:
    paths:
      - '.github/workflows/**'
  schedule:
    - cron: '0 0 * * 1'  # Exécution hebdomadaire le lundi à minuit
  workflow_dispatch:
    inputs:
      reason:
        description: 'Raison de l''exécution manuelle'
        required: false
        default: 'Vérification périodique'

jobs:
  actionlint:
    name: Actionlint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
        
      - name: Installation d'Actionlint
        run: |
          # Méthode d'installation plus fiable
          mkdir -p $HOME/bin
          curl -sSL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash | bash
          echo "$HOME/bin" >> $GITHUB_PATH
        
      - name: Vérification des workflows avec Actionlint
        id: actionlint
        run: |
          mkdir -p reports
          echo "Exécution d'actionlint sur les workflows..."
          
          # Exécution d'actionlint avec formatage pour GitHub Actions
          actionlint -color -format '{{range $err := .}}::error file={{$err.Filepath}},line={{$err.Line}},col={{$err.Column}}::{{$err.Message}}%0A```%0A{{$err.Snippet}}%0A```%0A{{end}}' > reports/actionlint-report.txt
          
          # Vérification du résultat
          if [ -s reports/actionlint-report.txt ]; then
            echo "has_errors=true" >> $GITHUB_OUTPUT
            echo "Des erreurs ont été détectées dans les workflows."
            cat reports/actionlint-report.txt
          else
            echo "has_errors=false" >> $GITHUB_OUTPUT
            echo "Aucune erreur détectée dans les workflows."
          fi

      - name: Enregistrement des problèmes détectés
        if: steps.actionlint.outputs.has_errors == 'true'
        run: |
          echo "## Problèmes détectés dans les workflows GitHub Actions" > reports/actionlint-summary.md
          echo "" >> reports/actionlint-summary.md
          echo "Des problèmes ont été détectés dans les workflows GitHub Actions. Veuillez corriger les erreurs suivantes:" >> reports/actionlint-summary.md
          echo "" >> reports/actionlint-summary.md
          cat reports/actionlint-report.txt >> reports/actionlint-summary.md
          
          # Afficher le rapport dans les logs
          echo "Rapport détaillé des problèmes:"
          cat reports/actionlint-summary.md

      - name: Création d'une issue pour les erreurs détectées
        if: steps.actionlint.outputs.has_errors == 'true'
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "⚠️ Problèmes détectés dans les workflows GitHub Actions"
          content-filepath: reports/actionlint-summary.md
          labels: bug, automation, workflow, ci-cd
          assignees: Casius999

      - name: Téléchargement du rapport
        uses: actions/upload-artifact@v3
        with:
          name: actionlint-report
          path: reports/
          retention-days: 30