name: Vérification d'Intégrité Basique

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Vérification basique
        run: |
          echo "Vérification d'intégrité basique réussie!"
          mkdir -p reports
          echo "# Rapport" > reports/report.md
          echo "Vérification réussie" >> reports/report.md
      - uses: actions/upload-artifact@v3
        with:
          name: integrity-report
          path: reports/
