name: "Workflow de Test avec Problèmes Corrigés"

on:
  # Ce workflow sera exécuté automatiquement
  workflow_dispatch:
  # Exécution sur un schedule valide (premier jour de chaque mois à 5h30)
  schedule:
    - cron: '30 5 1 * *'  # Le 1er de chaque mois à 5h30

# Ajout de permissions minimales selon les principes de moindre privilège
permissions:
  contents: read

jobs:
  test_job:
    runs-on: ubuntu-latest  # Version mise à jour d'Ubuntu
    timeout-minutes: 10  # Ajout d'un timeout pour éviter les exécutions bloquées
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Version à jour de checkout
        with:
          fetch-depth: 0  # Récupération complète de l'historique
      
      - name: Setup Node.js
        uses: actions/setup-node@v3  # Version à jour de setup-node
        with:
          node-version: '18.x'  # Version LTS plus récente
      
      - name: Set output
        id: set_var
        run: |
          echo "test_var=test_value" >> $GITHUB_OUTPUT  # Syntaxe moderne pour les outputs
      
      - name: Run tests
        run: |
          echo "Exécution des tests"
          echo "Ce workflow a été corrigé selon les meilleures pratiques"